name: Multi Environment Demo

on:
  push:
    branches:
      - develop
      - staging
      - main

jobs:
  deploy-dev:
    if: github.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest
    environment: Development

    steps:
      - run: |
          echo "${{ vars.MESSAGE }}"
          echo "Cluster: ${{ vars.CLUSTER_NAME }}"
          echo "Service: ${{ vars.SERVICE_NAME }}"

  deploy-stage:
    if: github.ref == 'refs/heads/staging'
    runs-on: ubuntu-latest
    environment: Staging

    steps:
      - run: |
          echo "${{ vars.MESSAGE }}"
          echo "Cluster: ${{ vars.CLUSTER_NAME }}"
          echo "Service: ${{ vars.SERVICE_NAME }}"

  deploy-prod:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment: Production

    steps:
      - run: |
          echo "${{ vars.MESSAGE }}"
          echo "Cluster: ${{ vars.CLUSTER_NAME }}"
          echo "Service: ${{ vars.SERVICE_NAME }}"
