name: Deploy Demo

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Choose the environment"
        required: true
        type: choice
        options:
          - Development
          - Staging
          - Production

jobs:
  deploy:
    runs-on: ubuntu-latest

    environment: ${{ inputs.environment }}

    steps:
      - name: Show Selected Environment
        run: |
          echo "Environment: ${{ inputs.environment }}"
          echo "Message: ${{ vars.MESSAGE }}"
          echo "App Name: ${{ vars.APP_NAME }}"
